[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[redirects]]
  from = "/*"
  to = "/index-modular.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
